///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace InstallationExe
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the InstallationExeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f6c6846d-4418-4f99-b795-0c0be196e5a8")]
    public partial class InstallationExeRepository : RepoGenBaseFolder
    {
        static InstallationExeRepository instance = new InstallationExeRepository();
        InstallationExeRepositoryFolders.FormMeAppFolder _formme;
        InstallationExeRepositoryFolders.FilesAppFolder _files;
        InstallationExeRepositoryFolders.OpenFileSecurityWarningAppFolder _openfilesecuritywarning;
        InstallationExeRepositoryFolders.UserAccountControlAppFolder _useraccountcontrol;
        InstallationExeRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the InstallationExeRepository element repository.
        /// </summary>
        [RepositoryFolder("f6c6846d-4418-4f99-b795-0c0be196e5a8")]
        public static InstallationExeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public InstallationExeRepository() 
            : base("InstallationExeRepository", "/", null, 0, false, "f6c6846d-4418-4f99-b795-0c0be196e5a8", ".\\RepositoryImages\\InstallationExeRepositoryf6c6846d.rximgres")
        {
            _formme = new InstallationExeRepositoryFolders.FormMeAppFolder(this);
            _files = new InstallationExeRepositoryFolders.FilesAppFolder(this);
            _openfilesecuritywarning = new InstallationExeRepositoryFolders.OpenFileSecurityWarningAppFolder(this);
            _useraccountcontrol = new InstallationExeRepositoryFolders.UserAccountControlAppFolder(this);
            _explorer = new InstallationExeRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f6c6846d-4418-4f99-b795-0c0be196e5a8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormMe folder.
        /// </summary>
        [RepositoryFolder("2408c940-a722-4f57-be74-4388e4a7c418")]
        public virtual InstallationExeRepositoryFolders.FormMeAppFolder FormMe
        {
            get { return _formme; }
        }

        /// <summary>
        /// The Files folder.
        /// </summary>
        [RepositoryFolder("cd413031-5095-4b5d-891e-30ca5fec5136")]
        public virtual InstallationExeRepositoryFolders.FilesAppFolder Files
        {
            get { return _files; }
        }

        /// <summary>
        /// The OpenFileSecurityWarning folder.
        /// </summary>
        [RepositoryFolder("cffc0bc7-b5a3-4ab1-a8c2-92fcc90c44fb")]
        public virtual InstallationExeRepositoryFolders.OpenFileSecurityWarningAppFolder OpenFileSecurityWarning
        {
            get { return _openfilesecuritywarning; }
        }

        /// <summary>
        /// The UserAccountControl folder.
        /// </summary>
        [RepositoryFolder("49284cef-47e6-47e9-9d59-d5953717d811")]
        public virtual InstallationExeRepositoryFolders.UserAccountControlAppFolder UserAccountControl
        {
            get { return _useraccountcontrol; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("dbe30556-2eba-4f67-b7af-866be70d6ba5")]
        public virtual InstallationExeRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class InstallationExeRepositoryFolders
    {
        /// <summary>
        /// The FormMeAppFolder folder.
        /// </summary>
        [RepositoryFolder("2408c940-a722-4f57-be74-4388e4a7c418")]
        public partial class FormMeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _instalation_textInfo;
            RepoItemInfo _installation_comboboxInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _installation_langInfo;
            RepoItemInfo _combobox1Info;
            RepoItemInfo _englishInfo;
            RepoItemInfo _button1Info;
            RepoItemInfo _checkbox1Info;
            RepoItemInfo _button2Info;
            RepoItemInfo _textblock2Info;
            RepoItemInfo _button11Info;

            /// <summary>
            /// Creates a new FormMe  folder.
            /// </summary>
            public FormMeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMe", "/form[@automationid='me']", parentFolder, 30000, null, true, "2408c940-a722-4f57-be74-4388e4a7c418", "")
            {
                _instalation_textInfo = new RepoItemInfo(this, "Instalation_Text", "text[@automationid='TextBlock_1']", 30000, null, "0699df43-5c12-4fb6-9373-b65bd128a735");
                _installation_comboboxInfo = new RepoItemInfo(this, "Installation_Combobox", "combobox[@automationid='ComboBox_1']/button", 30000, null, "79d52063-56cb-4a36-8c4c-b68a21859a27");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "combobox[@automationid='ComboBox_1']/button[@automationid='Button_1' and @text='OK']", 30000, null, "cf70a6a7-b570-4823-870a-cc0d29addfbe");
                _installation_langInfo = new RepoItemInfo(this, "Installation_Lang", "text[@text='English']", 30000, null, "06ed896c-e3c3-40c0-be75-4fe22cd970cf");
                _combobox1Info = new RepoItemInfo(this, "ComboBox1", "combobox[@automationid='ComboBox_1']", 30000, null, "4ade6881-1bf0-4cd5-bf8e-87fe1ed0d3b6");
                _englishInfo = new RepoItemInfo(this, "English", "combobox[@automationid='ComboBox_1']/?/?/text[@name='English']", 30000, null, "9469d1ff-59a7-4655-bbe9-2a9c1a80b128");
                _button1Info = new RepoItemInfo(this, "Button1", "combobox[@automationid='ComboBox_1']/button[@text='OK']", 30000, null, "7645d483-5b2e-4955-91d0-6b3f627013e6");
                _checkbox1Info = new RepoItemInfo(this, "CheckBox1", "container[@automationid='first']/checkbox[@automationid='CheckBox_1' and @text='I agree to the license terms']", 30000, null, "c53f6d53-ef4d-432c-bd55-ff2f5ccb6b5d");
                _button2Info = new RepoItemInfo(this, "Button2", "container[@automationid='first']/button[@automationid='Button_2']", 30000, null, "9eadde8e-942b-4611-9886-e4f09b7b87f0");
                _textblock2Info = new RepoItemInfo(this, "TextBlock2", "?/?/text[@automationid='TextBlock_2']", 30000, null, "ad617ebb-ef30-42e8-9c62-215d5a84423d");
                _button11Info = new RepoItemInfo(this, "Button11", "?/?/button[@automationid='Button_1']", 30000, null, "2652fc10-8b2c-43e6-9854-eaeef8b2570d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2408c940-a722-4f57-be74-4388e4a7c418")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2408c940-a722-4f57-be74-4388e4a7c418")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Instalation_Text item.
            /// </summary>
            [RepositoryItem("0699df43-5c12-4fb6-9373-b65bd128a735")]
            public virtual Ranorex.Text Instalation_Text
            {
                get
                {
                    return _instalation_textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Instalation_Text item info.
            /// </summary>
            [RepositoryItemInfo("0699df43-5c12-4fb6-9373-b65bd128a735")]
            public virtual RepoItemInfo Instalation_TextInfo
            {
                get
                {
                    return _instalation_textInfo;
                }
            }

            /// <summary>
            /// The Installation_Combobox item.
            /// </summary>
            [RepositoryItem("79d52063-56cb-4a36-8c4c-b68a21859a27")]
            public virtual Ranorex.Button Installation_Combobox
            {
                get
                {
                    return _installation_comboboxInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Installation_Combobox item info.
            /// </summary>
            [RepositoryItemInfo("79d52063-56cb-4a36-8c4c-b68a21859a27")]
            public virtual RepoItemInfo Installation_ComboboxInfo
            {
                get
                {
                    return _installation_comboboxInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("cf70a6a7-b570-4823-870a-cc0d29addfbe")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("cf70a6a7-b570-4823-870a-cc0d29addfbe")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Installation_Lang item.
            /// </summary>
            [RepositoryItem("06ed896c-e3c3-40c0-be75-4fe22cd970cf")]
            public virtual Ranorex.Text Installation_Lang
            {
                get
                {
                    return _installation_langInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Installation_Lang item info.
            /// </summary>
            [RepositoryItemInfo("06ed896c-e3c3-40c0-be75-4fe22cd970cf")]
            public virtual RepoItemInfo Installation_LangInfo
            {
                get
                {
                    return _installation_langInfo;
                }
            }

            /// <summary>
            /// The ComboBox1 item.
            /// </summary>
            [RepositoryItem("4ade6881-1bf0-4cd5-bf8e-87fe1ed0d3b6")]
            public virtual Ranorex.ComboBox ComboBox1
            {
                get
                {
                    return _combobox1Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1 item info.
            /// </summary>
            [RepositoryItemInfo("4ade6881-1bf0-4cd5-bf8e-87fe1ed0d3b6")]
            public virtual RepoItemInfo ComboBox1Info
            {
                get
                {
                    return _combobox1Info;
                }
            }

            /// <summary>
            /// The English item.
            /// </summary>
            [RepositoryItem("9469d1ff-59a7-4655-bbe9-2a9c1a80b128")]
            public virtual Ranorex.Text English
            {
                get
                {
                    return _englishInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The English item info.
            /// </summary>
            [RepositoryItemInfo("9469d1ff-59a7-4655-bbe9-2a9c1a80b128")]
            public virtual RepoItemInfo EnglishInfo
            {
                get
                {
                    return _englishInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("7645d483-5b2e-4955-91d0-6b3f627013e6")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("7645d483-5b2e-4955-91d0-6b3f627013e6")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The CheckBox1 item.
            /// </summary>
            [RepositoryItem("c53f6d53-ef4d-432c-bd55-ff2f5ccb6b5d")]
            public virtual Ranorex.CheckBox CheckBox1
            {
                get
                {
                    return _checkbox1Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBox1 item info.
            /// </summary>
            [RepositoryItemInfo("c53f6d53-ef4d-432c-bd55-ff2f5ccb6b5d")]
            public virtual RepoItemInfo CheckBox1Info
            {
                get
                {
                    return _checkbox1Info;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("9eadde8e-942b-4611-9886-e4f09b7b87f0")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("9eadde8e-942b-4611-9886-e4f09b7b87f0")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }

            /// <summary>
            /// The TextBlock2 item.
            /// </summary>
            [RepositoryItem("ad617ebb-ef30-42e8-9c62-215d5a84423d")]
            public virtual Ranorex.Text TextBlock2
            {
                get
                {
                    return _textblock2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextBlock2 item info.
            /// </summary>
            [RepositoryItemInfo("ad617ebb-ef30-42e8-9c62-215d5a84423d")]
            public virtual RepoItemInfo TextBlock2Info
            {
                get
                {
                    return _textblock2Info;
                }
            }

            /// <summary>
            /// The Button11 item.
            /// </summary>
            [RepositoryItem("2652fc10-8b2c-43e6-9854-eaeef8b2570d")]
            public virtual Ranorex.Button Button11
            {
                get
                {
                    return _button11Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button11 item info.
            /// </summary>
            [RepositoryItemInfo("2652fc10-8b2c-43e6-9854-eaeef8b2570d")]
            public virtual RepoItemInfo Button11Info
            {
                get
                {
                    return _button11Info;
                }
            }
        }

        /// <summary>
        /// The FilesAppFolder folder.
        /// </summary>
        [RepositoryFolder("cd413031-5095-4b5d-891e-30ca5fec5136")]
        public partial class FilesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplayInfo;

            /// <summary>
            /// Creates a new Files  folder.
            /// </summary>
            public FilesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Files", "/form[@title='Files']", parentFolder, 30000, null, true, "cd413031-5095-4b5d-891e-30ca5fec5136", "")
            {
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='ShellTabWindowClass']//element[@instance='1']//listitem[@automationid='3']/text[@automationid='System.ItemNameDisplay']", 30000, null, "4101fe3f-4b74-4add-956e-1c41337e8b13");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd413031-5095-4b5d-891e-30ca5fec5136")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd413031-5095-4b5d-891e-30ca5fec5136")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("4101fe3f-4b74-4add-956e-1c41337e8b13")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("4101fe3f-4b74-4add-956e-1c41337e8b13")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }
        }

        /// <summary>
        /// The OpenFileSecurityWarningAppFolder folder.
        /// </summary>
        [RepositoryFolder("cffc0bc7-b5a3-4ab1-a8c2-92fcc90c44fb")]
        public partial class OpenFileSecurityWarningAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonrunInfo;

            /// <summary>
            /// Creates a new OpenFileSecurityWarning  folder.
            /// </summary>
            public OpenFileSecurityWarningAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenFileSecurityWarning", "/form[@title>'Open File - Security Warn']", parentFolder, 30000, null, true, "cffc0bc7-b5a3-4ab1-a8c2-92fcc90c44fb", "")
            {
                _buttonrunInfo = new RepoItemInfo(this, "ButtonRun", "button[@text='&Run']", 30000, null, "40a43590-487d-45d3-b2f8-87f86caa1a82");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cffc0bc7-b5a3-4ab1-a8c2-92fcc90c44fb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cffc0bc7-b5a3-4ab1-a8c2-92fcc90c44fb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonRun item.
            /// </summary>
            [RepositoryItem("40a43590-487d-45d3-b2f8-87f86caa1a82")]
            public virtual Ranorex.Button ButtonRun
            {
                get
                {
                    return _buttonrunInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonRun item info.
            /// </summary>
            [RepositoryItemInfo("40a43590-487d-45d3-b2f8-87f86caa1a82")]
            public virtual RepoItemInfo ButtonRunInfo
            {
                get
                {
                    return _buttonrunInfo;
                }
            }
        }

        /// <summary>
        /// The UserAccountControlAppFolder folder.
        /// </summary>
        [RepositoryFolder("49284cef-47e6-47e9-9d59-d5953717d811")]
        public partial class UserAccountControlAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new UserAccountControl  folder.
            /// </summary>
            public UserAccountControlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UserAccountControl", "/form[@title='User Account Control']", parentFolder, 30000, null, true, "49284cef-47e6-47e9-9d59-d5953717d811", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("49284cef-47e6-47e9-9d59-d5953717d811")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("49284cef-47e6-47e9-9d59-d5953717d811")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("dbe30556-2eba-4f67-b7af-866be70d6ba5")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _troubleshootcompatibilityInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/contextmenu[@processname='explorer']", parentFolder, 30000, null, false, "dbe30556-2eba-4f67-b7af-866be70d6ba5", "")
            {
                _troubleshootcompatibilityInfo = new RepoItemInfo(this, "TroubleshootCompatibility", "?/?/menuitem[@accessiblename>'Troubleshoot compatibilit']", 30000, null, "cf293fed-4799-474e-9739-c74e163cac08");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dbe30556-2eba-4f67-b7af-866be70d6ba5")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dbe30556-2eba-4f67-b7af-866be70d6ba5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TroubleshootCompatibility item.
            /// </summary>
            [RepositoryItem("cf293fed-4799-474e-9739-c74e163cac08")]
            public virtual Ranorex.MenuItem TroubleshootCompatibility
            {
                get
                {
                    return _troubleshootcompatibilityInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The TroubleshootCompatibility item info.
            /// </summary>
            [RepositoryItemInfo("cf293fed-4799-474e-9739-c74e163cac08")]
            public virtual RepoItemInfo TroubleshootCompatibilityInfo
            {
                get
                {
                    return _troubleshootcompatibilityInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
