///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace InstallationExe
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("cd856794-e837-4269-b90f-fc731ac1aee6", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the InstallationExeRepository repository.
        /// </summary>
        public static InstallationExeRepository repo = InstallationExeRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'Files.SystemItemNameDisplay' at 114;17.", repo.Files.SystemItemNameDisplayInfo, new RecordItemIndex(0));
            repo.Files.SystemItemNameDisplay.Click(System.Windows.Forms.MouseButtons.Right, "114;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.TroubleshootCompatibility' at 176;2.", repo.Explorer.TroubleshootCompatibilityInfo, new RecordItemIndex(1));
            repo.Explorer.TroubleshootCompatibility.Click("176;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UserAccountControl' at 166;376.", repo.UserAccountControl.SelfInfo, new RecordItemIndex(2));
            repo.UserAccountControl.Self.Click("166;376");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.Button1' at 5;26.", repo.FormMe.Button1Info, new RecordItemIndex(3));
            repo.FormMe.Button1.Click("5;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.CheckBox1' at 8;6.", repo.FormMe.CheckBox1Info, new RecordItemIndex(4));
            repo.FormMe.CheckBox1.Click("8;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.Button2' at 96;54.", repo.FormMe.Button2Info, new RecordItemIndex(5));
            repo.FormMe.Button2.Click("96;54");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.TextBlock2' at 155;11.", repo.FormMe.TextBlock2Info, new RecordItemIndex(6));
            repo.FormMe.TextBlock2.Click("155;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1m.", new RecordItemIndex(7));
            Delay.Duration(60000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.TextBlock2' at 129;14.", repo.FormMe.TextBlock2Info, new RecordItemIndex(8));
            repo.FormMe.TextBlock2.Click("129;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.Button11' at 39;24.", repo.FormMe.Button11Info, new RecordItemIndex(9));
            repo.FormMe.Button11.Click("39;24");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
