///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c08e77fe-185b-4b48-8efa-a64132279f67")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.FormMeAppFolder _formme;
        MyTestRepositoryFolders.DesignerProV300096AppFolder _designerprov300096;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("c08e77fe-185b-4b48-8efa-a64132279f67")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "c08e77fe-185b-4b48-8efa-a64132279f67", ".\\RepositoryImages\\MyTestRepositoryc08e77fe.rximgres")
        {
            _formme = new MyTestRepositoryFolders.FormMeAppFolder(this);
            _designerprov300096 = new MyTestRepositoryFolders.DesignerProV300096AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c08e77fe-185b-4b48-8efa-a64132279f67")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormMe folder.
        /// </summary>
        [RepositoryFolder("6b1f86ab-57f2-4047-8ac3-08e1801c3f8c")]
        public virtual MyTestRepositoryFolders.FormMeAppFolder FormMe
        {
            get { return _formme; }
        }

        /// <summary>
        /// The DesignerProV300096 folder.
        /// </summary>
        [RepositoryFolder("a38a6059-4f68-45c3-8ab8-d86c67dda2ef")]
        public virtual MyTestRepositoryFolders.DesignerProV300096AppFolder DesignerProV300096
        {
            get { return _designerprov300096; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The FormMeAppFolder folder.
        /// </summary>
        [RepositoryFolder("6b1f86ab-57f2-4047-8ac3-08e1801c3f8c")]
        public partial class FormMeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _installation_textInfo;
            RepoItemInfo _installation_languageInfo;
            RepoItemInfo _buttonInfo;

            /// <summary>
            /// Creates a new FormMe  folder.
            /// </summary>
            public FormMeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMe", "/form[@automationid='me']", parentFolder, 30000, null, true, "6b1f86ab-57f2-4047-8ac3-08e1801c3f8c", "")
            {
                _installation_textInfo = new RepoItemInfo(this, "Installation_Text", "text[@automationid='TextBlock_1']", 30000, null, "be9e7199-9fae-4034-a238-a4a613f2f19d");
                _installation_languageInfo = new RepoItemInfo(this, "Installation_Language", "combobox[@automationid='ComboBox_1' and @selecteditemtext='English']", 30000, null, "e2fef229-f80e-472e-9798-d7336e9f92c1");
                _buttonInfo = new RepoItemInfo(this, "Button", "combobox[@automationid='ComboBox_1']/button[@automationid='Button_1']", 30000, null, "5dfe0c4c-7a3b-4fbc-9efd-137958cc1c32");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6b1f86ab-57f2-4047-8ac3-08e1801c3f8c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6b1f86ab-57f2-4047-8ac3-08e1801c3f8c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Installation_Text item.
            /// </summary>
            [RepositoryItem("be9e7199-9fae-4034-a238-a4a613f2f19d")]
            public virtual Ranorex.Text Installation_Text
            {
                get
                {
                    return _installation_textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Installation_Text item info.
            /// </summary>
            [RepositoryItemInfo("be9e7199-9fae-4034-a238-a4a613f2f19d")]
            public virtual RepoItemInfo Installation_TextInfo
            {
                get
                {
                    return _installation_textInfo;
                }
            }

            /// <summary>
            /// The Installation_Language item.
            /// </summary>
            [RepositoryItem("e2fef229-f80e-472e-9798-d7336e9f92c1")]
            public virtual Ranorex.ComboBox Installation_Language
            {
                get
                {
                    return _installation_languageInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Installation_Language item info.
            /// </summary>
            [RepositoryItemInfo("e2fef229-f80e-472e-9798-d7336e9f92c1")]
            public virtual RepoItemInfo Installation_LanguageInfo
            {
                get
                {
                    return _installation_languageInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("5dfe0c4c-7a3b-4fbc-9efd-137958cc1c32")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("5dfe0c4c-7a3b-4fbc-9efd-137958cc1c32")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }
        }

        /// <summary>
        /// The DesignerProV300096AppFolder folder.
        /// </summary>
        [RepositoryFolder("a38a6059-4f68-45c3-8ab8-d86c67dda2ef")]
        public partial class DesignerProV300096AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _englishInfo;

            /// <summary>
            /// Creates a new DesignerProV300096  folder.
            /// </summary>
            public DesignerProV300096AppFolder(RepoGenBaseFolder parentFolder) :
                    base("DesignerProV300096", "/contextmenu[@processname='DesignerPro_V30.00.96']", parentFolder, 30000, null, false, "a38a6059-4f68-45c3-8ab8-d86c67dda2ef", "")
            {
                _englishInfo = new RepoItemInfo(this, "English", "?/?/listitem[@text='English']", 30000, null, "73ec0adf-f04d-4a7b-9337-723e457ad010");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a38a6059-4f68-45c3-8ab8-d86c67dda2ef")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a38a6059-4f68-45c3-8ab8-d86c67dda2ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The English item.
            /// </summary>
            [RepositoryItem("73ec0adf-f04d-4a7b-9337-723e457ad010")]
            public virtual Ranorex.ListItem English
            {
                get
                {
                    return _englishInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The English item info.
            /// </summary>
            [RepositoryItemInfo("73ec0adf-f04d-4a7b-9337-723e457ad010")]
            public virtual RepoItemInfo EnglishInfo
            {
                get
                {
                    return _englishInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
